### PR TITLE
to handle dynamically created structr buttons

### PR DESCRIPTION
**Pull request by l-1**
structr-app.js hadn't been able to handle dynamically created elements including one's loaded with ajax, proposed modification allows to handle them.

PS: I agree with Contributor License Agreement at https://structr.org/cla

### CODE REVIEW

**Comment by vigorouscoding** [comment]
This looks interesting - thank you for contributing!
The [jQuery documentation for delegate](http://api.jquery.com/delegate/) states that `As of jQuery 1.7, .delegate() has been superseded by the .on() method`.
Structr includes jQuery v1.11.1 and thus IMO should use "on" if possible.
Does this also work with "on"?

````
// jQuery 1.4.3+
$( elements ).delegate( selector, events, data, handler );
// jQuery 1.7+
$( elements ).on( events, selector, data, handler );
````

**Comment by l-1** [comment]
With original code `'$(sel).on('click', ... etc` doesn't work. It can be checked with creating page A and B. Page A load's page B div #pageB-div which contains editable element with code like this 
`$('#pageA-div').load('/page-b/' + this.id + ' #pageB-div');`
where this.id is id of repeater element, for example.

Yes, I overlooked that `.on()` method can be used the same way. So the new line of code is
`$(document).on('click', sel, function(e) {`
which yet changes the original structr-app.js, but also works.

**Comment by vigorouscoding** [comment]
Perfect, thanks for checking this. If you want to update your pull request I will happily merge it into master. As long as the PR is open you can just commit in your fork and the PR gets updated automatically.

**Comment by l-1** [comment]
Thanks for your help!

Like this?

**Comment by vigorouscoding** [comment]
Thanks for updating the PR - I just merged it :)

**Pull request merged**
