### PR TITLE
 * now it is possible to make a "not" and query.

### PR DESCRIPTION
**Pull request by dlaske**
Create a query to filter with one or more search values to get a result without this values. 
Use the char "^" to create a not query.
i.e you could do the following rest call: 

curl -i "http://localhost:8082/entities/onlineShops?pageSize=10&page=1&sid=^1887;11605"
- get 10 onlineShops without shops with sids 1887;11605

curl -i "http://localhost:8082/entities/onlineShops?pageSize=10&page=1&sid=^1887"
- or filter only the 10 shops without the sid "1887"

### CODE REVIEW

**Comment by amorgner** [comment]
Thanks for this PR, looks really interesting!

I'd love to merge it, but as this is a non-trivial change, we need to make sure that this is working as expected under as many circumstances as possible.

Would you mind adding a couple of tests? Maybe the best starting point would be the https://github.com/structr/structr/blob/master/structr-rest/src/test/java/org/structr/rest/test/AdvancedSearchTest.java - you could just clone this test and modify it to reflect the changes you made.

**Comment by dlaske** [comment]
Ok I write tests for this feature. But it will take a few days. ;-)

**Comment by amorgner** [comment]
No worries. We could also assist you in writing tests, or do it together. Maybe have a skype/phone call this or next week?

**Comment by dlaske** [comment]
First i try it on my own. But when i have questions i ask you or christian at skype.

**Comment by dlaske** [comment]
I've added a new testmethod which tests the two aspects i've explained above.

**Comment by dlaske** [comment]
now i'm working on an alternative method like loose to make only a wildcard search with one field.
The lucene query must look like this: 

+(program_Id:124) +(name = "blue" name = "*blue*") -(price = "0.00")

the rest query looks like this

http://localhost:8082/entities/articles?name=blau&pageSize=30&page=1&inExactProperty=name&program_Id=10773&price=^0.00

**Comment by dlaske** [comment]
In a few days i will add more tests.

**Comment by cmorgner** [comment]
This pull request is outdated, closing.

**Pull request closed without merging**
