### PR TITLE
add incremental compiling

### PR DESCRIPTION
**Pull request by mingfang**

### CODE REVIEW

**Comment by cmorgner** [comment]
Hi mingfang,

thank you very much for the pull request and the work you've done! I tested the changes with the current master, and our test suite finishes without errors, so this is a very good sign. I'm very happy to merge the PR after my colleagues and I have tested the changes in some more projects.

However there is one thing that you need to do so that I can merge the PR. Can you please agree to our Contributor License Agreement at https://structr.com/CLA? You can simply state here that you agree to the CLA, or send an e-mail to info@structr.com that you agree to the CLA.

Apart from some more testing on our side, this is really the only thing that needs to be done in order to merge the PR. We are very much looking forward to having a partial / incremental compile, so I'm eager to merge. :)

Thanks and best regards,
Christian

**Comment by eric-schleicher** [comment]
dropping by from the ether to make note that this is an awesome improvement!   :)

**Comment by mingfang** [comment]
> Hi mingfang,
> 
> thank you very much for the pull request and the work you've done! I tested the changes with the current master, and our test suite finishes without errors, so this is a very good sign. I'm very happy to merge the PR after my colleagues and I have tested the changes in some more projects.
> 
> However there is one thing that you need to do so that I can merge the PR. Can you please agree to our Contributor License Agreement at https://structr.com/CLA? You can simply state here that you agree to the CLA, or send an e-mail to [info@structr.com](mailto:info@structr.com) that you agree to the CLA.
> 
> Apart from some more testing on our side, this is really the only thing that needs to be done in order to merge the PR. We are very much looking forward to having a partial / incremental compile, so I'm eager to merge. :)
> 
> Thanks and best regards,
> Christian

I hereby agree to the CLA.

**Comment by mingfang** [comment]
I've made the final changes to this PR.
It now supports adding and deleting classes properly.
Also I cleanup up the changes so that most of the logic is in NodeExtender and very little impact on other files.
I feel this is now ready for your consideration to merge.

**Comment by cmorgner** [comment]
Hi mingfang,

I'm really sorry and embarrassed, but I have to tell you that I made a mistake when I tested your changes yesterday night. I forgot to actually apply the changes to the newly created branch (i.e. I only did the first step of the two steps from the "Merging via command line" instructions), and that's why all the tests passed.

Today I tested again with the correct steps, and I have to tell you that there are a number issues with the pull request. Some weeks ago, I spent several days to test a solution very similar to yours to speed up the compilation process, so I know some of the pitfalls.

The most critical issue is that two versions of the same class are not considered equal() nor assignableFrom() when they come from two different compile cycles. After compiling, Structr caches the Class objects in various places to be able to validate the node type when connecting nodes with each other. If we now re-build only one of the two classes of a relationship (e.g. by adding a property or changing a view etc.), the assignment fails because the two Class objects are not compatible (although they represent the exact same class):

`{
  "code": 422,
  "message": "Node type mismatch",
  "errors": [
    {
      "type": "Test2",
      "property": null,
      "token": "must_be_of_type",
      "detail": "Test2"
    }
  ]
}`

You can reproduce the issue by creating two node types and a relationship between them, then change one of the classes and try to assign them to each other afterwards.

I encountered the exact same problems when I tried to implement partial compilation. It is not sufficient to compile the class that was changed; you need to follow all the relationships that this class has, and add all these classes to the partial build as well. And because these classes change as well, you need to add the related classes of those as well, recursively, until you added the whole graph of related types to the partial build. And this is not even the full picture, because the class objects are stored in many different places and are used for all kinds of lookups etc.

I really want to make partial compilation work in Structr, but I think there are still a lot of problems to solve before we can merge this pul request. Sorry that I didn't catch that earlier!

I'm happy to work with you on the changes and share my knowledge of the internal workings of Structr, so feel free to ask questions and send changes for us to test! I hope we can make this work!

With best regards,
Christian

**Comment by mingfang** [comment]
@cmorgner 
Thanks for the detail explanation of the problem.
Can you please tell me which unit tests are failing?
(Sorry my local copy has many failing tests due to my ArangoDb changes)

**Comment by cmorgner** [comment]
@mingfang here are the test results for the three most important modules, structr-core, structr-rest and structr-ui:

structr-core:
no failures

structr-rest:
```
[ERROR]   DocumentTest.testNestedUpdate:1428->createSchemaNode:1966->StructrRestTestBase.createEntity:261 1 expectation failed.
Expected status code <201> doesn't match actual status code <422>.
[INFO] 
[ERROR] Tests run: 222, Failures: 1, Errors: 0, Skipped: 0
```

structr-ui:
```
[ERROR]   AdvancedSchemaTest.testSchemaPropertyOrderInInheritedViews:895 Invalid number of properties in sorted view expected:<7> but was:<0>
[ERROR]   Deployment0Test.test01SimplePage:64->DeploymentTestBase.compare:63->DeploymentTestBase.compare:83 Invalid deployment roundtrip result
[ERROR]   Deployment0Test.test02aVisibilities:78->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test02bVisibilities:153->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test02cVisibilities:228->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test02dVisibilities:303->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test03ContentTypes:375->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test04ContentTypes:412->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test05SimpleTemplateInPage:448->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test06SimpleTemplateInSharedComponents:483->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test07SimpleSharedTemplate:510->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test08SharedTemplateInTwoPages:539->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test09SharedTemplatesWithChildren:580->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment0Test.test10SharedComponent:623->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment1Test.test11TemplateInTbody:90->DeploymentTestBase.compare:63->DeploymentTestBase.compare:83 Invalid deployment roundtrip result
[ERROR]   Deployment1Test.test12EmptyContentElementWithContentType:102->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment1Test.test13EmptyContentElement:132->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment1Test.test16SharedTemplateWithChildren:297->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment1Test.test17NamedNonSharedTemplateWithChildren:331->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment1Test.test18NonNamedNonSharedTemplateWithChildren:364->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment1Test.test19HtmlEntities:396->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment1Test.test20ExportOwnership:443->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment2Test.test21ExportGrants:116->DeploymentTestBase.compare:83 Invalid deployment roundtrip result
[ERROR]   Deployment2Test.test22TemplateOwnershipAndGrants:145->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment2Test.test24ContentShowConditions:283->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment2Test.test26Escaping:376->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment2Test.test30IncreasingIndentationCountInRoundtrip:581->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment3Test.test31RoundtripWithEmptyContentElements:122->DeploymentTestBase.compare:63->DeploymentTestBase.compare:83 Invalid deployment roundtrip result
[ERROR]   Deployment3Test.test32RoundtripWithEmptyContentElements:133->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment3Test.test34WidgetWithTemplate:224->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment3Test.test35WidgetWithSharedComponentCreation:291->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment3Test.test36BuiltInTypesWithProperties:392 » NullPointer
[ERROR]   Deployment3Test.test37SharedComponentTemplate:424 » NullPointer
[ERROR]   Deployment3Test.test40TwoTemplatesWithSameNameInTwoPages:543->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment4Test.test41CustomAttributes:97->DeploymentTestBase.compare:63->DeploymentTestBase.compare:83 Invalid deployment roundtrip result
[ERROR]   Deployment4Test.test42NamedContentElement:108->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment4Test.test43HiddenContentElement:135->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment4Test.test44HiddenPage:166->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   Deployment4Test.test47NestedSharedComponents:457->DeploymentTestBase.createElement:340 » NullPointer
[ERROR]   DiffTest.testBlockMoveDown:505->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testBlockMoveUp:464->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testInsertDivBranch:94->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testInsertDivBranch2:115->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testInsertHeading:75->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testInsertMultipleTextNodes:139->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testModifyMultipleTextNodes2:165->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testModifyRemoveAttributes:417->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testModifyTag:575->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testMove:302->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testReparentOneLevel:193->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testReparentThreeLevels:259->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testReparentTwoLevels:225->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testReplaceContent:58->compare:742 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   DiffTest.testSurroundBlock:541->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testSwap:341->compare:742 Tag name mismatch expected:<#doctype> but was:<html>
[ERROR]   DiffTest.testTreeRemovalFix:613 Wrong number of divs returned from node query expected:<4> but was:<0>
[ERROR]   ImporterTest.testBootstrapJumbotronEditModeWidget:230->compare:518 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   ImporterTest.testNewsfeedWidget:334->compare:518 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   ImporterTest.testScriptAttributes:395->compare:518 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   ImporterTest.testWidgetWithScriptTags:363->compare:518 Tag name mismatch expected:<#text> but was:<body>
[ERROR]   UserSelfRegistrationTest.testUserSelfRegistrationWithRedirect:183 » NullPointer
[ERROR]   BasicAuthTest.test02BasicAuthOnPageWithErrorPage:209 » NullPointer
[ERROR]   BasicAuthTest.test03BasicAuthOnFileWithErrorPage:261 » NullPointer
[ERROR]   DOMAndPageTest.test01CreatePage:116->StructrUiTest.makePublic:488 » NullPointer
[ERROR]   DOMAndPageTest.test01DOMChildren:398 » NullPointer
[ERROR]   DOMAndPageTest.test01PagePerformance:636->StructrUiTest.makePublic:488 » NullPointer
[ERROR]   DOMAndPageTest.testAccessFlagsForPages:1130 » NullPointer
[ERROR]   DOMAndPageTest.testHttpResponseHeaders:927 » NullPointer
[ERROR]   DOMAndPageTest.testIncreasePageVersion:972 » NullPointer
[ERROR]   DOMAndPageTest.testNameCheckInDOMNode:1043 » NullPointer
[ERROR]   DOMAndPageTest.testPagePath:813 » NullPointer
[ERROR]   DOMAndPageTest.testPublicAccessToSharedComponent:1060->createElement:1201 » NullPointer
[ERROR]   DOMAndPageTest.testSharedComponentShowConditionError:1095->createElement:1201 » NullPointer
[ERROR]   DOMAndPageTest.testSiblingPerformance:443
[ERROR]   HtmlServletObjectResolvingTest.testObjectResolvingInHtmlServlet:84 » NullPointer
[ERROR]   RenderContextTest.testVariableReplacement:399 » NullPointer
[ERROR]   SiteTest.test02Sites:107 » NullPointer
[ERROR]   UiScriptingTest.testElementAttributeScripting:893 » NullPointer
[ERROR]   UiScriptingTest.testFunctionQueryWithJavaScriptAndRepeater:446 » NullPointer
[ERROR]   UiScriptingTest.testIncludeWithRepeaterInJavaScript:497 » NullPointer
[ERROR]   UiScriptingTest.testKeywordShortcutsInJavaScript:1128 » NullPointer
[ERROR]   UiScriptingTest.testRestQueryRepeater:567 » NullPointer
[ERROR]   UiScriptingTest.testRestQueryWithRemoteAttributeRepeater:624 » NullPointer
[ERROR]   UiScriptingTest.testScriptReplacement:1076 » NullPointer
[ERROR]   UiScriptingTest.testScripting:320 » NullPointer
[ERROR]   XPathTest.testXPathAttributes:140 » NullPointer
[ERROR]   ContentTest.testSplitText:51
[ERROR]   DOMElementTest.testAttributeNodeMethods:118 NullPointer
[ERROR]   DOMElementTest.testGetTagName:50 NullPointer
[ERROR]   DOMNodeTest.testAppendChildErrors:336
[ERROR]   DOMNodeTest.testAppendWithFragment:677 » ClassCast class org.structr.dynamic.P...
[ERROR]   DOMNodeTest.testGetChildNodes:166
[ERROR]   DOMNodeTest.testGetParentNode:132
[ERROR]   DOMNodeTest.testInsertBefore:476
[ERROR]   DOMNodeTest.testInsertBeforeWithFragment:598 » ClassCast class org.structr.dyn...
[ERROR]   DOMNodeTest.testNormalize:756 » ClassCast class org.structr.dynamic.Page canno...
[ERROR]   DOMNodeTest.testRemoveChildNode:210
[ERROR]   DOMNodeTest.testReplaceChild:417
[ERROR]   DOMNodeTest.testReplaceChildWithFragment:520 » ClassCast class org.structr.dyn...
[ERROR]   DOMNodeTest.testSiblingMethods:285
[ERROR]   PageTest.testCloneNode:347 Unexpected exception
[ERROR]   PageTest.testClonePageWithTemplateNode:415 NullPointer
[ERROR]   PageTest.testGetElementsByTagName:117 Unexpected exception
[ERROR]   PageTest.testImportNodesDeep:280 Unexpected exception
[INFO] 
[ERROR] Tests run: 278, Failures: 106, Errors: 0, Skipped: 0
```

**Comment by mingfang** [comment]
@cmorgner I fixed the issues and those unit tests are now passing. I also simplified the code a little.

**Comment by cmorgner** [comment]
The updated version of this PR passes all tests, happy to merge! :tada:

**Pull request merged**
