### PR TITLE
switch to github repo for google-diff-match-patch

### PR DESCRIPTION
**Pull request by nmervaillie**
PR for #453

### CODE REVIEW

**Comment by cmorgner** [comment]
Hi Nicolas,

thank you for the quick fix and the pull request!

In order for me to be able to merge the PR, you need to accept the Structr Contributor License Agreement at https://structr.org/cla . You can do so by simply stating that you agree here in the comments.

-Christian

**Comment by cmorgner** [comment]
Hi again,

it seems that the repository in question is a private mirror of the diff-patch-match code which we unfortunately cannot use.

A quick check revealed that the library is not actively used in Structr, so we will just remove it from the dependencies.

Thank you for bringing this up!

Best,
Christian

**Comment by nmervaillie** [comment]
OK, fine !
closing the PR, then

**Comment by amorgner** [comment]
We finally fixed this, thanks for your input!

**Pull request closed without merging**
